# Generated by Django 4.1 on 2022-09-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_userid_profilelink_owner_profilebiogram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d/', verbose_name='Wgraj zdjęcie'),
        ),
    ]
