# Generated by Django 4.1 on 2022-08-08 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilelink',
            old_name='userid',
            new_name='owner',
        ),
    ]
