# Generated by Django 4.1 on 2022-08-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_userid_profilelink_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilelink',
            name='bio',
            field=models.CharField(max_length=350, null=True, verbose_name='Opis...'),
        ),
    ]
