# Generated by Django 4.1 on 2022-08-20 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_profilebiogram_profilelink_biogram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilelink',
            name='biogram',
        ),
        migrations.CreateModel(
            name='ProfileBiogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biogram', models.CharField(max_length=350, null=True, verbose_name='Opis...')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profilelink')),
            ],
        ),
    ]
