# Generated by Django 4.1 on 2022-08-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_profilelink_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilelink',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/uploads/avatars/% Y/% m/% d/'),
        ),
    ]
