# Generated by Django 4.1 on 2022-08-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_profilelink_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilelink',
            name='avatar',
        ),
        migrations.AddField(
            model_name='profilebiogram',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/uploads/avatars/% Y/% m/% d/'),
        ),
    ]
